stages:
  - test
Node.js v8.x.x:
  stage: test
  image: node:8
  script:
    - npm config set spin false
    - npm install
    - npm run build
    - npm test
    - npm run coverage
    - npm run docs
  artifacts:
    paths:
      - coverage/
      - docs/